# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

User.create([
  { :provider => "twitter", :uid => "111373627", :name => "Eric MacAdie", :email => "user@example.com", :created_at => "2012-09-30 04:01:47", :updated_at => "2012-09-30 04:03:43", :number_of_sites => 5, :is_admin => false }
], :without_protection => true )



Website.create([
  { :url => "http://www.theoildrum.com/", :minute => 4, :name => "Oil Drum", :summary => "adf", :failed_tries => 0, :successful_tries => 0, :user_id => 1, :created_at => "2012-09-30 04:02:52", :updated_at => "2012-09-30 04:02:52", :good_site => true },
  { :url => "http://akka.io", :minute => 4, :name => "Akka", :summary => "A", :failed_tries => 0, :successful_tries => 0, :user_id => 1, :created_at => "2012-09-30 04:03:05", :updated_at => "2012-09-30 04:03:05", :good_site => true },
  { :url => "http://en.memory-alpha.org/wiki/Star_Trek:_Enterprise", :minute => 1, :name => "Star_Trek: Enterprise", :summary => "asdf", :failed_tries => 0, :successful_tries => 0, :user_id => 1, :created_at => "2012-09-30 04:03:16", :updated_at => "2012-09-30 04:03:16", :good_site => true },
  { :url => "http://guides.rubyonrails.org", :minute => 5, :name => "Rails Guides", :summary => "sadf", :failed_tries => 0, :successful_tries => 0, :user_id => 1, :created_at => "2012-09-30 04:03:32", :updated_at => "2012-09-30 04:03:32", :good_site => true },
  { :url => "http://weather.yahoo.com", :minute => 1, :name => "Yahoo Weather", :summary => "asdf", :failed_tries => 0, :successful_tries => 0, :user_id => 1, :created_at => "2012-09-30 04:03:43", :updated_at => "2012-09-30 04:03:43", :good_site => true }
], :without_protection => true )


